- name: Patch tripleo-api missing parameter_defaults
  patch: src=../files/add-missing-parameter-defaults.patch
         dest=/home/stack/rhci-tripleo-api/tripleo_api/deploy.py
         backup=yes
  tags:
    - tripleo-api
    - tripleo-api-missing-parameter-defaults
    - tripleo-api-patches

