- name: Copy undercloud.conf
  copy: src=/usr/share/instack-undercloud/undercloud.conf.sample dest=/home/stack/undercloud.conf force=no

- name: Enable mistral in undercloud.conf
  ini_file: dest=/home/stack/undercloud.conf section=DEFAULT option=enable_mistral value=true backup=yes

- name: Enable zaqar in undercloud.conf
  ini_file: dest=/home/stack/undercloud.conf section=DEFAULT option=enable_zaqar value=true
