- name: Clone tripleo-common repository
  git: repo=https://git.openstack.org/openstack/tripleo-common
       dest=/home/stack/tripleo-common
       update=no
  tags:
    - tripleo-common
    - tripleo-common-update

- name: Add patch to remove unneeded files from plan creation
  patch: src=../files/2ed727b4.diff
         dest=/home/stack/tripleo-common/tripleo_common/utils/tarball.py
         backup=yes
  tags:
    - tripleo-common
    - tripleo-common-plan-tarball-patch

- name: Remove existing tripleo-common installation
  shell: rm -Rf /usr/lib/python2.7/site-packages/tripleo_common*
  sudo: yes
  tags:
    - tripleo-common
    - tripleo-common-update

- name: Install tripleo-common from source
  shell: python setup.py install
  args:
    chdir: /home/stack/tripleo-common
  sudo: yes
  tags:
    - tripleo-common
    - tripleo-common-update

- name: Restart systemctl restart openstack-mistral-executor
  shell: systemctl restart openstack-mistral-executor
  sudo: yes
  tags:
    - tripleo-common
    - tripleo-common-update

- name: Restart systemctl restart openstack-mistral-engine
  shell: systemctl restart openstack-mistral-engine
  sudo: yes
  tags:
    - tripleo-common
    - tripleo-common-update

- name: Populate mistral db
  shell: mistral-db-manage populate
  sudo: yes
  tags:
    - tripleo-common
    - tripleo-common-update

- name: Check plan_management workbook
  shell: source ~/stackrc && mistral workbook-list | grep tripleo.plan_management.v1 | wc -l
  register: plan_management_playbook_exists
  args:
    executable: /bin/bash
  tags:
    - tripleo-common
    - tripleo-workbooks

- name: Create plan_management workbook
  shell: source ~/stackrc && mistral workbook-create /home/stack/tripleo-common/workbooks/plan_management.yaml
  when: plan_management_playbook_exists.stdout == "0"
  args:
    executable: /bin/bash
  tags:
    - tripleo-common
    - tripleo-workbooks

- name: Update plan_management workbook
  shell: source ~/stackrc && mistral workbook-update /home/stack/tripleo-common/workbooks/plan_management.yaml
  when: plan_management_playbook_exists.stdout == "1"
  args:
    executable: /bin/bash
  tags:
    - tripleo-common
    - tripleo-workbooks

- name: Check baremetal workbook
  shell: source ~/stackrc && mistral workbook-list | grep tripleo.baremetal.v1 | wc -l
  register: baremetal_playbook_exists
  args:
    executable: /bin/bash
  tags:
    - tripleo-common
    - tripleo-workbooks

- name: Create baremetal workbook
  shell: source ~/stackrc && mistral workbook-create /home/stack/tripleo-common/workbooks/baremetal.yaml
  when: baremetal_playbook_exists.stdout == "0"
  args:
    executable: /bin/bash
  tags:
    - tripleo-common
    - tripleo-workbooks

- name: Update baremetal workbook
  shell: source ~/stackrc && mistral workbook-update /home/stack/tripleo-common/workbooks/baremetal.yaml
  when: baremetal_playbook_exists.stdout == "1"
  args:
    executable: /bin/bash
  tags:
    - tripleo-common
    - tripleo-workbooks

- name: Check deployment workbook
  shell: source ~/stackrc && mistral workbook-list | grep tripleo.deployment.v1 | wc -l
  register: deployment_playbook_exists
  args:
    executable: /bin/bash
  tags:
    - tripleo-common
    - tripleo-workbooks

- name: Create deployment workbook
  shell: source ~/stackrc && mistral workbook-create /home/stack/tripleo-common/workbooks/deployment.yaml
  when: deployment_playbook_exists.stdout == "0"
  args:
    executable: /bin/bash
  tags:
    - tripleo-common
    - tripleo-workbooks

- name: Update deployment workbook
  shell: source ~/stackrc && mistral workbook-update /home/stack/tripleo-common/workbooks/deployment.yaml
  when: deployment_playbook_exists.stdout == "1"
  args:
    executable: /bin/bash
  tags:
    - tripleo-common
    - tripleo-workbooks

- name: Check for default plan
  shell: source ~/stackrc && swift list | grep overcloud | wc -l
  register: default_plan_exists
  args:
    executable: /bin/bash
  tags:
    - tripleo-common
    - default-plan

- name: Get default plan workflow id
  shell: source ~/stackrc && mistral workflow-list | grep tripleo.plan_management.v1.create_default_deployment_plan | cut -d' ' -f2
  register: default_plan_workflow_id
  when: default_plan_exists.stdout == "0"
  args:
    executable: /bin/bash
  tags:
    - tripleo-common
    - default-plan
  
- name: Create default plan
  shell: source ~/stackrc && mistral execution-create {{ default_plan_workflow_id.stdout }} '{"container":"overcloud"}'
  when: default_plan_exists.stdout == "0"
  tags:
    - tripleo-common
    - default-plan
  args:
    executable: /bin/bash
