- name: Set cors allowed_origin in /etc/keystone/keystone.conf
  ini_file: dest="/etc/keystone/keystone.conf" section=cors option=allowed_origin value=* backup=yes
  sudo: yes

- name: Restart httpd
  service: name=httpd state=restarted
  sudo: yes

- name: Set cors allowed_origin in /etc/ironic/ironic.conf
  ini_file: dest="/etc/ironic/ironic.conf" section=cors option=allowed_origin value=* backup=yes
  sudo: yes

- name: Set cors allow_headers in /etc/ironic/ironic.conf
  ini_file: dest="/etc/ironic/ironic.conf" section=cors option=allow_headers value=Content-Type,Cache-Control,Content-Language,Expires,Last-Modified,Pragma,X-Auth-Token
  sudo: yes

- name: Restart ironic api 
  service: name=openstack-ironic-api state=restarted
  sudo: yes
  ignore_errors: yes
  
- name: Set cors allowed_origin in /etc/heat/heat.conf
  ini_file: dest="/etc/heat/heat.conf" section=cors option=allowed_origin value=* backup=yes
  sudo: yes
  
- name: Restart heat api 
  service: name=openstack-heat-api state=restarted
  sudo: yes
  
- name: Set cors allowed_origin in /etc/mistral/mistral.conf
  ini_file: dest="/etc/mistral/mistral.conf" section=cors option=allowed_origin value=* backup=yes
  sudo: yes
  
- name: Restart mistral api 
  service: name=openstack-mistral-api state=restarted
  sudo: yes
  
- name: Set cors_allow_origin in /etc/swift/proxy-server.conf
  ini_file: dest="/etc/swift/proxy-server.conf" section=DEFAULT option=cors_allow_origin value=* backup=yes
  sudo: yes
  
- name: Restart swift proxy 
  service: name=openstack-swift-proxy state=restarted
  sudo: yes
